-- Tabela: projetos
CREATE TABLE projetos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR,
    descricao TEXT,
    api_meta VARCHAR,
    id_pagina NUMERIC,
    id_instagram TEXT,
    url_destino TEXT,
    Publico TEXT,
    id_conta TEXT,
    id_pixel TEXT,
    utm_padrao TEXT
);

-- Tabela: copy
CREATE TABLE copy (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao_video TEXT,
    titulo VARCHAR,
    call_to_action VARCHAR,
    id_projeto INTEGER,
    roteiro TEXT,
    tipo TEXT,
    status TEXT,
    CONSTRAINT fk_copy_projeto FOREIGN KEY (id_projeto) REFERENCES projetos(id)
);

-- Tabela: criativos
CREATE TABLE criativos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR,
    url_download TEXT,
    status VARCHAR,
    id_copy INTEGER,
    CONSTRAINT fk_criativo_copy FOREIGN KEY (id_copy) REFERENCES copy(id)
);

-- Tabela: campanhas
CREATE TABLE campanhas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR,
    id_meta TEXT,
    status VARCHAR,
    id_criativo INTEGER,
    id_projeto INTEGER,
    CONSTRAINT fk_campanha_criativo FOREIGN KEY (id_criativo) REFERENCES criativos(id),
    CONSTRAINT fk_campanha_projeto FOREIGN KEY (id_projeto) REFERENCES projetos(id)
);
